import pandas as pd
import os

def count_cells_by_subclass():
    """
    Loads the cell summary CSV and counts the number of cells per subclass.
    """
    # Define the path to the input CSV file
    # This file was generated by the 'merge_celltypes_eachregion.py' script
    in_dir = '/scratch/mfafouti/Mommybrain/Slide_seq/RCTD/WMB_reference_coronal'
    csv_path = os.path.join(in_dir, 'cell_subclass_summary.csv')

    # --- Load Data ---
    if not os.path.exists(csv_path):
        print(f"❌ Error: The file '{csv_path}' was not found.")
        print("Please make sure you have run 'merge_celltypes_eachregion.py' first.")
        return

    print(f"📄 Loading data from: {csv_path}")
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"❌ An error occurred while reading the CSV file: {e}")
        return

    # --- Count Cells ---
    subclass_column = 'subclass'
    if subclass_column not in df.columns:
        print(f"❌ Error: Column '{subclass_column}' not found in the CSV file.")
        print(f"   Available columns are: {df.columns.tolist()}")
        return

    print("\n🔬 Counting cells per subclass...")
    subclass_counts = df[subclass_column].value_counts().sort_index()

    print("\n📊 Number of cells in each subclass:")
    print("-" * 40)
    print(subclass_counts.to_string())
    print("-" * 40)
    print(f"\nTotal number of subclasses found: {len(subclass_counts)}")
    print(f"Total number of cells counted: {df.shape[0]}")


    # --- Save Counts to CSV ---
    print("\n💾 Saving counts to CSV...")
    counts_df = subclass_counts.reset_index()
    counts_df.columns = ['subclass', 'cell_count']

    output_csv_path = os.path.join(in_dir, 'smaller_ref_subclass_counts_stratified_subsampled.csv')
    try:
        counts_df.to_csv(output_csv_path, index=False)
        print(f"✅ Successfully saved counts to: {output_csv_path}")
        print("CSV preview:")
        print(counts_df.head().to_string())
    except Exception as e:
        print(f"❌ An error occurred while saving the CSV file: {e}")


if __name__ == '__main__':
    count_cells_by_subclass()

