[settings]
h5ad_path    = /scratch/mfafouti/Mommybrain/Slide_seq/Spatial/plot_genes/data/All_RCTD_types_singlet_score_0_slide_seq_15_named.h5ad
samples      = ["B41", "B03", "B14"]
sample_col   = sample
celltype_col = RCTD_first_type_rat
spatial_key  = X_spatial
point_size   = 2
port         = 8050
debug        = false
color_csv    = /scratch/mfafouti/Mommybrain/cluster_annotation_term.csv
gene_list    = /scratch/mfafouti/Mommybrain-PPD/Slide_seq/Spatial/plot_genes/list/DE_tags_gene_list.csv
output_html  = /scratch/mfafouti/Mommybrain-PPD/Slide_seq/Spatial/plot_genes/spatial_viewer.html
out_dir      = /scratch/mfafouti/Mommybrain-PPD/Slide_seq/Spatial/plot_genes/viewer_data
port_static  = 8080
