RUN_NAME="seq_test"
H5AD_FILE="/scratch/mfafouti/Mommybrain/Slide_seq/keons_single_cell/out/subset_objects/adata_neurons_181663.h5ad"
COMPARISONS_CSV="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR/seq_comparisons.csv"
CELLTYPE_COL="RCTD_first_type_rat"
GENE_SYMBOL_COL="name"