RUN_NAME="tags_qlf_test"
H5AD_FILE="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR/DE_after_mt_filter_108123_mincells_10_in_2_samples_slide_tags.h5ad"
COMPARISONS_CSV="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR/tags_comparisons.csv"
CELLTYPE_COL="subclass_name"
GENE_SYMBOL_COL="gene_symbol"
EDGER_MODEL="lrt"   # options: "lrt" (glmLRT) or "qlf" (glmQLFit)