# ==========================================================================
# EdgeR Pipeline Config
# Usage: bash scripts/run_pipeline.sh config/run_config.conf
# ==========================================================================

# ========== RUN ==========
RUN_NAME="merge_imn"
H5AD_FILE="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR/data/DE_after_mt_filter_108123_mincells_10_in_2_samples_slide_tags.h5ad"
COMPARISONS_CSV="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR/data/comparisons.csv"

# ========== COLUMNS ==========
CELLTYPE_COL="subclass_name"
GENE_SYMBOL_COL="gene_symbols"

# ========== ENVIRONMENT ==========
SC_ENV="anndata_env"

# ========== PATHS ==========
WORKSPACE="/scratch/mfafouti/Mommybrain/Slide_tags/EdgeR"
APPTAINER_SIF="/scratch/mfafouti/docker/edger.sif"

# ========== MERGE CELL TYPES ==========
MERGE_CELLTYPES=("038 DG-PIR Ex IMN" "045 OB-STR-CTX Inh IMN")
MERGE_LABEL="038-045 IMN"
